default_stages:
  - commit

repos:
- repo: local
  hooks:
  - id: isort
    name: isort
    language: python
    entry: isort
    types:
      - python

  - id: black
    name: black
    language: python
    entry: black
    types:
      - python

  - id: flake8
    name: flake8
    language: python
    entry: flake8 core
    require_serial: true
    types:
      - python

- repo: https://github.com/jorisroovers/gitlint
  rev: v0.13.1
  hooks:
  - id: gitlint
